<?php

namespace Database\Seeders;

use App\Models\MarkerScoringProfile;
use Illuminate\Database\Seeder;

class MarkerScoringProfilesSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = [
            [
                'slug' => 'general-adult',
                'name' => 'General adult',
                'profile_type' => 'general',
                'gender' => null,
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => null,
                'conditions' => null,
                'description' => 'Базовый профиль оценки для взрослого пользователя без специальных факторов риска.',
                'is_default' => true,
            ],
            [
                'slug' => 'male-adult',
                'name' => 'Male adult',
                'profile_type' => 'sex',
                'gender' => 'male',
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => null,
                'conditions' => null,
                'description' => 'Профиль оценки для взрослых мужчин.',
                'is_default' => false,
            ],
            [
                'slug' => 'female-adult',
                'name' => 'Female adult',
                'profile_type' => 'sex',
                'gender' => 'female',
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => false,
                'risk_factors' => null,
                'conditions' => null,
                'description' => 'Профиль оценки для взрослых женщин вне беременности.',
                'is_default' => false,
            ],
            [
                'slug' => 'female-pregnant',
                'name' => 'Pregnant female',
                'profile_type' => 'female_specific',
                'gender' => 'female',
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => true,
                'risk_factors' => null,
                'conditions' => ['pregnancy'],
                'description' => 'Профиль оценки для беременных женщин.',
                'is_default' => false,
            ],
            [
                'slug' => 'female-postmenopause',
                'name' => 'Postmenopause female',
                'profile_type' => 'female_specific',
                'gender' => 'female',
                'age_min' => 45,
                'age_max' => null,
                'pregnant' => false,
                'risk_factors' => null,
                'conditions' => ['postmenopause'],
                'description' => 'Профиль оценки для женщин в постменопаузе.',
                'is_default' => false,
            ],
            [
                'slug' => 'senior',
                'name' => 'Senior',
                'profile_type' => 'age',
                'gender' => null,
                'age_min' => 60,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => null,
                'conditions' => null,
                'description' => 'Профиль оценки для пользователей старшего возраста.',
                'is_default' => false,
            ],
            [
                'slug' => 'child',
                'name' => 'Child',
                'profile_type' => 'age',
                'gender' => null,
                'age_min' => 0,
                'age_max' => 12,
                'pregnant' => null,
                'risk_factors' => null,
                'conditions' => null,
                'description' => 'Профиль оценки для детей.',
                'is_default' => false,
            ],
            [
                'slug' => 'teen',
                'name' => 'Teen',
                'profile_type' => 'age',
                'gender' => null,
                'age_min' => 13,
                'age_max' => 17,
                'pregnant' => null,
                'risk_factors' => null,
                'conditions' => null,
                'description' => 'Профиль оценки для подростков.',
                'is_default' => false,
            ],
            [
                'slug' => 'cardiovascular-risk',
                'name' => 'Cardiovascular risk',
                'profile_type' => 'risk',
                'gender' => null,
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => ['cardiovascular_risk'],
                'conditions' => null,
                'description' => 'Профиль оценки для пользователей с повышенным сердечно-сосудистым риском.',
                'is_default' => false,
            ],
            [
                'slug' => 'insulin-resistance',
                'name' => 'Insulin resistance',
                'profile_type' => 'risk',
                'gender' => null,
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => ['insulin_resistance'],
                'conditions' => null,
                'description' => 'Профиль оценки для риска инсулинорезистентности и нарушений углеводного обмена.',
                'is_default' => false,
            ],
            [
                'slug' => 'iron-deficiency-risk',
                'name' => 'Iron deficiency risk',
                'profile_type' => 'risk',
                'gender' => null,
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => ['iron_deficiency_risk'],
                'conditions' => null,
                'description' => 'Профиль оценки для риска дефицита железа.',
                'is_default' => false,
            ],
            [
                'slug' => 'thyroid-risk',
                'name' => 'Thyroid risk',
                'profile_type' => 'risk',
                'gender' => null,
                'age_min' => 18,
                'age_max' => null,
                'pregnant' => null,
                'risk_factors' => ['thyroid_risk'],
                'conditions' => null,
                'description' => 'Профиль оценки для риска нарушений функции щитовидной железы.',
                'is_default' => false,
            ],
        ];

        foreach ($profiles as $profile) {
            MarkerScoringProfile::updateOrCreate(
                ['slug' => $profile['slug']],
                [
                    ...$profile,
                    'source' => 'DSlog MVP scoring profile',
                    'is_active' => true,
                ]
            );
        }
    }
}